//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonGrade
    {
        public int gradeID { get; set; }
        public Nullable<int> studentID { get; set; }
        public Nullable<int> lessonID { get; set; }
        public Nullable<byte> visa { get; set; }
        public Nullable<byte> final { get; set; }
        public Nullable<byte> quiz { get; set; }
        public Nullable<double> avrg { get; set; }
        public Nullable<bool> stat { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
