//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.LessonGrades = new HashSet<LessonGrade>();
        }
    
        public int studentID { get; set; }
        public string studentName { get; set; }
        public string studentSurname { get; set; }
        public string studentTC { get; set; }
        public Nullable<System.DateTime> studentBirthDate { get; set; }
        public string studentMail { get; set; }
        public string studentPhoto { get; set; }
        public Nullable<bool> studentSex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonGrade> LessonGrades { get; set; }
    }
}
