//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentID { get; set; }
        public int memberID { get; set; }
        public decimal payAmount { get; set; }
        public Nullable<bool> paymentState { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
